### ISSUE TITLE
build failure (debian "stretch")

### ISSUE THREAD

**Issue by warner** [sodiumoxide/sodiumoxide#244]
Maybe I'm missing something, but current trunk doesn't build for me on my linux box (debian/stretch, rustc 1.28.0, I've got `clang` installed so I made it past the surprising "cannot find `stddef.h`" errors, `libsodium-dev` 1.0.11-2 installed from a debian package).

There's one batch of errors like this:

```
error[E0432]: unresolved import `ffi::crypto_stream_xchacha20`
 --> src/crypto/stream/xchacha20.rs:5:11
  |
5 | use ffi::{crypto_stream_xchacha20,
  |           ^^^^^^^^^^^^^^^^^^^^^^^ no `crypto_stream_xchacha20` in the root. Did you mean to use `crypto_stream_chacha20`?
```

and another set like:

```
error[E0308]: mismatched types
  --> src/newtype_macros.rs:32:20
   |
32 |               memcmp(&self.0, &other.0)
   |                      ^^^^^^^ expected slice, found array
   | 
  ::: src/crypto/stream/xchacha20.rs:11:1
   |
11 | / stream_module!(crypto_stream_xchacha20,
12 | |                crypto_stream_xchacha20_xor,
13 | |                crypto_stream_xchacha20_xor_ic,
14 | |                crypto_stream_xchacha20_KEYBYTES,
15 | |                crypto_stream_xchacha20_NONCEBYTES);
   | |___________________________________________________- in this macro invocation
   |
   = note: expected type `&[u8]`
              found type `&[u8; _]`
```

(34 errors in total).

Is this happening because the bindings are written against a newer version of libsodium? Maybe #231 would help out here, or #234, or even including a full copy of libsodium in this repo.. it'd be great if downstream crates could just depend upon `sodiumoxide` and not have to worry about what's already installed on the system or not.

thanks,
 -Brian

**Comment by jamessewell** [comment]
Doesn't build for me either on CentOS 7.2

**Comment by nvesely** [comment]
Hi @warner,

First, I just wanted to say I'm a big fan of your work!

Anyway, I'm also on Debian stretch and am not able to reproduce the errors you're getting here. To be clear, by building the current trunk you mean the HEAD of the `master` branch? I have the same version of libsodium installed (in fact, I had only installed `libsodium` and not `libsodium-dev` until now) and I have both clang 3.8 and 6.0 (the latter is from https://apt.llvm.org/ and appears to be set as the default install) on my system.

According to the [`rust-bindgen` documentation](https://rust-lang-nursery.github.io/rust-bindgen/requirements.html):

> If you are generating bindings to C++, you almost definitely want 3.9 or greater.

Can you try either installing clang 5.0 or 6.0 using the LLVM official repos (or installing clang 5.0 from stretch-backports if you prefer)? @jamessewell can you also try with clang >= 3.9 and report your results?

I have made a proposal in https://github.com/sodiumoxide/sodiumoxide/issues/234#issuecomment-414797999 which would implement both #231 and #234.  I wanted to get at least some positive feedback on the idea from co-maintainers and users before proceeding in this direction (so feel free to leave your thoughts in that thread).

At this point there is no intention of doing anything similar with clang, which certainly seems less simple. At the least however, we might add a note to our README specifying clang 3.9 or higher is required (and perhaps even a higher minimum number, as some `bindgen` features need as high as clang 5.0 to work--we'll have to see if we need any of those).

**Comment by katyo** [comment]
Installing *libsodium-dev **1.0.16-2~bpo9+1*** complettely solves this issue.

**Comment by nvesely** [comment]
Short term fix: #248. Long-term fix: #234.

**Comment by nvesely** [comment]
Can you confirm the this builds when using the compiler and library versions specified in the README? @warner

**Comment by jendakol** [comment]
Hey @nvesely, I ran into a similar issue like this. Unfortunately recommendations you made in the readme didn't help.
Currently I have plain Debian 9 (I'm building something in Docker actually, using `debian:9-slim`) with _stretch-backports_, have installed `libsodium-dev=1.0.16-2~bpo9+1` and `clang-5.0` but still getting a ton of errors like those above :cry:  
Can provide you the Dockerfile, if it helps.

**Comment by nvesely** [comment]
@jendakol Yeah, go ahead and post the Dockerfile. I suspect that even though the correct versions are installed, they might be installed alongside earlier versions, and are not set as the default. We'll see though.

**Comment by jendakol** [comment]
@nvesely Here it is: https://github.com/jendakol/sodiumoxide-problem (It maybe contains even some unrelated stuff, it's derived from my use-case, but I believe it doesn't matter.)

BTW it works on my own system (Ubuntu 18.04) with clang 6.0. Any idea how to get clang 6.0 to Debian 9? :smiley:

**Comment by jendakol** [comment]
OK, I tried to change the base to `ubuntu:bionic` and everything works (there is clang 6.0 installed).

**Comment by jendakol** [comment]
Does closing of this mean it's fixed?

**Comment by nvesely** [comment]
Afaict. If someone can show with certainty it's failing using the recommended versions they can re-open it.

**Comment by jendakol** [comment]
I am a little bit confused right now. Your docs state `Clang >= 3.9` right now however I tried and anything below 6.0 just doesn't work. Is that uncertain? :-)

**Comment by JorisBolsens** [comment]
I have clang-9.0 installed on debian stretch and am still running into this issue:

```
clang --version
clang version 9.0.0-svn354826-1~exp1+0~20190225221945.1090~1.gbpd90386 (trunk)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```bash
error[E0432]: unresolved imports `ffi::crypto_stream_xchacha20`, `ffi::crypto_stream_xchacha20_xor`, `ffi::crypto_stream_xchacha20_xor_ic`, `ffi::crypto_stream_xchacha20_KEYBYTES`, `ffi::crypto_stream_xchacha20_NONCEBYTES`
 --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/stream/xchacha20.rs:5:11
  |
5 | use ffi::{crypto_stream_xchacha20,
  |           ^^^^^^^^^^^^^^^^^^^^^^^ no `crypto_stream_xchacha20` in the root. Did you mean to use `crypto_stream_chacha20`?
6 |           crypto_stream_xchacha20_xor,
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `crypto_stream_xchacha20_xor` in the root. Did you mean to use `crypto_stream_chacha20_xor`?
7 |           crypto_stream_xchacha20_xor_ic,
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `crypto_stream_xchacha20_xor_ic` in the root. Did you mean to use `crypto_stream_chacha20_xor_ic`?
8 |           crypto_stream_xchacha20_KEYBYTES,
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `crypto_stream_xchacha20_KEYBYTES` in the root. Did you mean to use `crypto_stream_chacha20_KEYBYTES`?
9 |           crypto_stream_xchacha20_NONCEBYTES};
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `crypto_stream_xchacha20_NONCEBYTES` in the root. Did you mean to use `crypto_stream_chacha20_NONCEBYTES`?

error[E0425]: cannot find value `crypto_kx_PUBLICKEYBYTES` in module `ffi`
 --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:6:40
  |
6 | pub const PUBLICKEYBYTES: usize = ffi::crypto_kx_PUBLICKEYBYTES as usize;
  |                                        ^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `crypto_box_PUBLICKEYBYTES`?

error[E0425]: cannot find value `crypto_kx_SECRETKEYBYTES` in module `ffi`
 --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:9:40
  |
9 | pub const SECRETKEYBYTES: usize = ffi::crypto_kx_SECRETKEYBYTES as usize;
  |                                        ^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `crypto_box_SECRETKEYBYTES`?

error[E0425]: cannot find value `crypto_kx_SEEDBYTES` in module `ffi`
  --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:12:35
   |
12 | pub const SEEDBYTES: usize = ffi::crypto_kx_SEEDBYTES as usize;
   |                                   ^^^^^^^^^^^^^^^^^^^ did you mean `crypto_box_SEEDBYTES`?

error[E0425]: cannot find value `crypto_kx_SESSIONKEYBYTES` in module `ffi`
  --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:15:41
   |
15 | pub const SESSIONKEYBYTES: usize = ffi::crypto_kx_SESSIONKEYBYTES as usize;
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `crypto_box_SECRETKEYBYTES`?

error[E0425]: cannot find function `crypto_kx_keypair` in module `ffi`
  --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:55:14
   |
55 |         ffi::crypto_kx_keypair(pk.0.as_mut_ptr(), sk.0.as_mut_ptr());
   |              ^^^^^^^^^^^^^^^^^ did you mean `crypto_box_keypair`?

error[E0425]: cannot find function `crypto_kx_seed_keypair` in module `ffi`
  --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:66:14
   |
66 |         ffi::crypto_kx_seed_keypair(pk.0.as_mut_ptr(), sk.0.as_mut_ptr(), seed.0.as_ptr());
   |              ^^^^^^^^^^^^^^^^^^^^^^ did you mean `crypto_box_seed_keypair`?

error[E0425]: cannot find function `crypto_kx_server_session_keys` in module `ffi`
  --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:84:18
   |
84 |             ffi::crypto_kx_server_session_keys(
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function `crypto_kx_client_session_keys` in module `ffi`
   --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:112:18
    |
112 |             ffi::crypto_kx_client_session_keys(
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0080]: evaluation of constant value failed
  --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/stream/stream_macros.rs:27:17
   |
27 |       nonce Nonce(NONCEBYTES);
   |                   ^^^^^^^^^^ referenced constant has errors
   | 
  ::: /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/stream/xchacha20.rs:11:1
   |
11 | / stream_module!(crypto_stream_xchacha20,
12 | |                crypto_stream_xchacha20_xor,
13 | |                crypto_stream_xchacha20_xor_ic,
14 | |                crypto_stream_xchacha20_KEYBYTES,
15 | |                crypto_stream_xchacha20_NONCEBYTES);
   | |___________________________________________________- in this macro invocation

error[E0080]: evaluation of constant value failed
  --> /home/epicblood/.cargo/registry/src/github.com-1ecc6299db9ec823/sodiumoxide-0.1.0/src/crypto/kx/x25519blake2b.rs:19:22
   |
19 |     public PublicKey(PUBLICKEYBYTES);
   |                      ^^^^^^^^^^^^^^ referenced constant has errors

error: aborting due to 11 previous errors

Some errors occurred: E0080, E0425, E0432.
For more information about an error, try `rustc --explain E0080`.
error: Could not compile `sodiumoxide`.
```

**Comment by kpp** [comment]
@JorisBolsens please try to update rustc and try to build sodiumoxide from master

**Comment by Dylan-DPC** [comment]
i think it is better we take this to a new issue (even though it is sort of a duplicate)

**Comment by JorisBolsens** [comment]
@kpp rustc is latest version
`rustc 1.32.0 (9fda7c223 2019-01-16)` 

sodium is being compiled as a dependency in another library, not sure how i would update it to use master

@Dylan-DPC I was hoping I was just doing something wrong, I can definitely make a new issue if thats not the case.

**Comment by Dylan-DPC** [comment]
even if you are doing something wrong, you can open an issue, nothing wrong with that.
